server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lms-exam-system
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms_exam_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

mybatis:
  type-aliases-package: com.lms.exam.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: lms-exam-system-secret-key-must-be-at-least-256-bits-for-hs256-algorithm
  expiration: 86400000
springdoc:
  api-docs:
    path: /v3/api-docs                    # /api 제거
  swagger-ui:
    path: /swagger-ui.html                # 단순화
    url: /v3/api-docs                     # /api 제거
    config-url: /v3/api-docs/swagger-config  # /api 제거
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    root: INFO
    com.lms.exam: DEBUG
